name: Python application test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Use the API key
      run: |
      env:
        DEVCONTAINER_PATH: .devcontainer/devcontainer.json
        echo "API key: ${{ secrets.API_KEY }}"

    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        pytest --cov=.
