name: Python application test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Debug API key
      run: env

    - name: Debug API Key Secret
      run: |
       echo "API key secret: ${{ secrets.API_KEY }}"

    - name: Set Environment
      run: |
        echo "#################"
      env:
        API_KEY: ${{ secrets.API_KEY }}
        DEVCONTAINER_PATH: .devcontainer/devcontainer.json
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        pytest --cov=.
